"""
data_loader.py
--------------
Unified data loader for AERIS.
Automatically uses real RVVCCA data if available,
falls back to synthetic data for development/testing.
"""

import pandas as pd
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from config import BASE_PATH


def load_air_quality(
    filename: str = None,
    prefer_real: bool = True,
) -> pd.DataFrame:
    """
    Load air quality data for AERIS.

    Priority order (when prefer_real=True):
      1. data/raw/air_quality_real.csv   — real RVVCCA data (fetched by rvvcca_ingestion.py)
      2. data/raw/air_quality.csv        — synthetic data (generated by synthetic_data.py)

    Parameters
    ----------
    filename     : Override filename. If None, auto-selects based on prefer_real.
    prefer_real  : If True, looks for real data first.

    Returns
    -------
    pd.DataFrame in AERIS standard format.
    """
    candidates = []

    if filename:
        candidates = [filename]
    elif prefer_real:
        candidates = ["air_quality_real.csv", "air_quality.csv"]
    else:
        candidates = ["air_quality.csv"]

    for fname in candidates:
        path = os.path.join(BASE_PATH, "raw", fname)
        if os.path.exists(path):
            print(f"Loading: {path}")
            df = pd.read_csv(path, parse_dates=["datetime"])
            df.columns = [c.lower().strip() for c in df.columns]
            print(f"  {len(df):,} rows | {df['station'].nunique()} stations "
                  f"| {df['datetime'].min().date()} → {df['datetime'].max().date()}")
            return df

    raise FileNotFoundError(
        f"No data file found. Run one of:\n"
        f"  python src/rvvcca_ingestion.py          (real data)\n"
        f"  python src/synthetic_data.py            (synthetic data)"
    )


def load_weather(filename: str = "weather.csv") -> pd.DataFrame:
    """Load a standalone weather CSV if it exists."""
    path = os.path.join(BASE_PATH, "raw", filename)
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Weather file not found: {path}\n"
            f"Note: the RVVCCA dataset includes wind/temp/humidity — "
            f"a separate weather file is only needed for supplementary met data."
        )
    df = pd.read_csv(path, parse_dates=["datetime"])
    df.columns = [c.lower().strip() for c in df.columns]
    return df
