"""
inject_findings.py
------------------
Injects pipeline-derived findings into the two-tab strata_portfolio.html.

Each dataset has its own sentinel block:
  2021-2022 hourly : // __STRATA_2122_START__ ... // __STRATA_2122_END__
  2024 daily       : // __STRATA_2024_START__ ... // __STRATA_2024_END__

Usage:
  python src/inject_findings.py --dataset 2122
  python src/inject_findings.py --dataset 2024
  python src/inject_findings.py --dataset 2122 --findings path/to/findings.json
  python src/inject_findings.py --dataset 2024 --dry-run

Data flow enforced:
  strata_processed.csv → analysis.py → findings.json
  → inject_findings.py --dataset [2122|2024] → strata_portfolio.html

NO scientific values are hardcoded here. Every number comes from findings.json.
"""

import json, os, sys, math, argparse
from datetime import datetime

sys.path.insert(0, os.path.dirname(__file__))
from config import OUTPUT_PATH

FINDINGS_2122 = os.path.join(OUTPUT_PATH, "reports", "strata_findings_2122.json")
FINDINGS_2024 = os.path.join(OUTPUT_PATH, "reports", "strata_findings.json")
DEFAULT_HTML  = os.path.join(os.path.dirname(__file__), "..", "strata_portfolio.html")

SENTINELS = {
    "2122": ("// __STRATA_2122_START__", "// __STRATA_2122_END__"),
    "2024": ("// __STRATA_2024_START__", "// __STRATA_2024_END__"),
}

# ── Colour maps ───────────────────────────────────────────────────────────────
AM_COLORS = {
    "stagnant_mix":    "#1e2e3c",
    "marine_air":      "#00d4ff",
    "saharan_dust":    "#ff9a00",
    "urban_pollution": "#ff4455",
}
AM_LABELS = {
    "stagnant_mix":    "Stagnant mix",
    "marine_air":      "Marine air",
    "saharan_dust":    "Saharan dust",
    "urban_pollution": "Urban pollution",
}
CORR_COLORS = {
    "no2":            "#ff4455",
    "temperature":    "#ff9a00",
    "pm25":           "#ffb347",
    "ACI_normalized": "#8b6fff",
    "pm10":           "#ff9a00",
    "o3":             "#00d4ff",
    "wind_speed":     "#39d98a",
    "humidity":       "#3a5060",
}
CORR_LABELS = {
    "no2":            "NO\u2082",
    "temperature":    "Temperature",
    "pm25":           "PM2.5",
    "ACI_normalized": "ACI",
    "pm10":           "PM10",
    "o3":             "O\u2083",
    "wind_speed":     "Wind speed",
    "humidity":       "Humidity",
}
SEASON_COLORS = {
    "Winter": "#00d4ff",
    "Spring": "#39d98a",
    "Summer": "#ff9a00",
    "Autumn": "#ff4455",
}
STATION_COORDS = {
    "Avda. Francia":     {"lat": 39.4632, "lon": -0.3451},
    "Bulevar Sur":       {"lat": 39.4501, "lon": -0.3928},
    "Bulevard Sud":      {"lat": 39.4501, "lon": -0.3928},
    "Conselleria Meteo": {"lat": 39.4700, "lon": -0.3700},
    "Molino del Sol":    {"lat": 39.4447, "lon": -0.3802},
    "Molí del Sol":      {"lat": 39.4447, "lon": -0.3802},
    "Nazaret Meteo":     {"lat": 39.4540, "lon": -0.3370},
    "Pista Silla":       {"lat": 39.4298, "lon": -0.4083},
    "Politecnico":       {"lat": 39.4800, "lon": -0.3463},
    "Politècnic":        {"lat": 39.4800, "lon": -0.3463},
    "Centro":            {"lat": 39.4698, "lon": -0.3763},
    "Centre":            {"lat": 39.4698, "lon": -0.3763},
    "Viveros":           {"lat": 39.4793, "lon": -0.3640},
    "Vivers":            {"lat": 39.4793, "lon": -0.3640},
    "Valencia Centre":   {"lat": 39.4698, "lon": -0.3763},
    "Valencia Olivereta":{"lat": 39.4720, "lon": -0.4060},
    "Conselleria":       {"lat": 39.4700, "lon": -0.3700},
}

def _f(val, d=3):
    if val is None or (isinstance(val, float) and math.isnan(val)):
        return 0.0
    return round(float(val), d)

def _coord(name, key):
    if name in STATION_COORDS:
        return STATION_COORDS[name][key]
    for k, v in STATION_COORDS.items():
        if k.lower() in name.lower() or name.lower() in k.lower():
            return v[key]
    return 0.0

# ── Block builders ────────────────────────────────────────────────────────────

def build_2122_block(findings: dict) -> str:
    """Build the JS data block for the 2021-2022 hourly dataset."""
    s    = findings["summary"]
    prov = findings["provenance"]
    c    = findings.get("calima", {})
    # Normalise calima field names — aeris_findings uses n_hours, newer uses n_days
    if "n_hours" in c and "n_days" not in c:
        c = dict(c)
        c["n_days"] = c.get("n_hours", 0)
        c["n_obs"]  = c.get("n_hours", 0)
    if "pct_of_valid_obs" not in c and "pct_of_valid_hours" in c:
        c = dict(c); c["pct_of_valid_obs"] = c["pct_of_valid_hours"]
    pm   = findings.get("pm10_stats", {})
    # Normalise pm10_stats — aeris uses max_datetime, newer uses max_date
    if "max_datetime" in pm and "max_date" not in pm:
        pm = dict(pm)
        pm["max_date"] = str(pm["max_datetime"])[:10]
    diur = findings.get("diurnal", {})
    stations = findings.get("stations", [])
    corr     = findings.get("correlations", {})
    am_list  = findings.get("air_mass", [])

    START, END = SENTINELS["2122"]
    lines = [
        START,
        "// GENERATED BY inject_findings.py --dataset 2122 — DO NOT EDIT MANUALLY",
        f"// Source   : {prov.get('dataset','RVVCCA 2021-2022 hourly')}",
        f"// Generated: {prov.get('generated_at','unknown')}",
        f"// Pipeline : v{prov.get('pipeline_version','?')}",
        f"// Rows     : {s.get('n_obs',0):,} valid station-hours",
        "",
    ]

    # STATIONS_2122
    st_rows = []
    for st in stations:
        name = st.get("station","")
        lat  = _f(st.get("latitude") or _coord(name,"lat"), 4)
        lon  = _f(st.get("longitude") or _coord(name,"lon"), 4)
        cal_val = int(st.get('calima_hours', st.get('calima_days', 0)))
        st_rows.append(
            f"  {{station:{name!r},lat:{lat},lon:{lon},"
            f"pm10:{_f(st.get('pm10_mean',0),1)},pm25:{_f(st.get('pm25_mean',0),1)},"
            f"no2:{_f(st.get('no2_mean',0),1)},o3:{_f(st.get('o3_mean',0),1)},"
            f"aqi_sci:{_f(st.get('cmpi_mean',0),2)},aqi_public:{_f(st.get('public_mean',0),2)},"
            f"aqi_div:{_f(st.get('aqi_div_mean',0),4)},aqi_div_max:{_f(st.get('aqi_div_max',0),2)},"
            f"calima:{cal_val},"
            f"aci:{_f(st.get('aci_mean',0),4)},n_obs:{int(st.get('n_obs',0))}}}"
        )
    lines += ["const STATIONS_2122=[", ",\n".join(st_rows), "];", ""]

    # HOURLY_DIV — 24 values of mean divergence by hour
    # aeris_findings uses diurnal.divergence_array (list of 24 floats)
    # or diurnal.hourly (dict keyed by hour string)
    div_array = diur.get("divergence_array", [])
    hourly_dict = diur.get("hourly", {})
    hours_list  = diur.get("hours", [])

    if div_array and len(div_array) == 24:
        hd_arr = [_f(v, 4) for v in div_array]
    elif hourly_dict:
        hd_arr = [_f(hourly_dict.get(str(h), hourly_dict.get(h, 0)), 4) for h in range(24)]
    elif hours_list:
        hd_map = {r.get("hour", r.get("hora", i)): r.get("aqi_divergence", 0)
                  for i, r in enumerate(hours_list)}
        hd_arr = [_f(hd_map.get(h, 0), 4) for h in range(24)]
    else:
        hd_arr = [0.0] * 24
    lines.append(f"const HOURLY_DIV=[{','.join(str(v) for v in hd_arr)}];")

    # REAL_NO2, REAL_O3, REAL_PM10
    # aeris_findings stores per-pollutant hourly arrays inside diurnal.hourly
    # as nested dicts: {"no2": {0: val, 1: val, ...}, ...}
    # or as flat lists in diurnal.no2_array etc.
    for col, jsname in [("no2","REAL_NO2"),("o3","REAL_O3"),("pm10","REAL_PM10")]:
        col_data = diur.get(f"{col}_array", diur.get(col, None))
        if isinstance(col_data, list) and len(col_data) == 24:
            # Dedicated array for this pollutant
            arr = [_f(v, 2) for v in col_data]
        elif isinstance(hourly_dict, list) and len(hourly_dict) > 0:
            # aeris_findings: hourly is a list of dicts [{hour:0, no2:16.2, o3:51.4, ...}, ...]
            hmap = {r.get("hour", i): r.get(col, 0) for i, r in enumerate(hourly_dict)}
            arr = [_f(hmap.get(h, 0), 2) for h in range(24)]
        elif isinstance(hourly_dict, dict) and len(hourly_dict) > 0:
            # hourly is a dict keyed by hour string/int
            arr = [_f(hourly_dict.get(str(h), hourly_dict.get(h, {})).get(col, 0)
                      if isinstance(hourly_dict.get(str(h), hourly_dict.get(h, {})), dict)
                      else 0, 2) for h in range(24)]
        elif isinstance(col_data, dict):
            arr = [_f(col_data.get(str(h), col_data.get(h, 0)), 2) for h in range(24)]
        elif hours_list:
            col_map = {r.get("hour", r.get("hora", i)): r.get(col, 0)
                       for i, r in enumerate(hours_list)}
            arr = [_f(col_map.get(h, 0), 2) for h in range(24)]
        else:
            arr = [0.0] * 24
        lines.append(f"const {jsname}=[{','.join(str(v) for v in arr)}];")
    lines.append("")

    # CORR_DATA_2122
    corr_rows = []
    for col, val in corr.items():
        label = CORR_LABELS.get(col, col)
        color = CORR_COLORS.get(col, "#3a5060")
        corr_rows.append(f"  {{var:{label!r},r:{_f(val,4)},color:{color!r}}}")
    lines += ["const CORR_DATA_2122=[", ",\n".join(corr_rows), "];", ""]

    # AM_DATA_2122
    am_parts = []
    for row in am_list:
        key   = row.get("air_mass_type","unknown")
        color = AM_COLORS.get(key,"#3a5060")
        label = AM_LABELS.get(key,key)
        am_parts.append(
            f"{key}:{{n:{int(row.get('count',0))},pct:{_f(row.get('pct',0),2)},"
            f"div:{_f(row.get('mean_div',0),4)},color:{color!r},label:{label!r}}}"
        )
    lines += ["const AM_DATA_2122={", ",\n".join(am_parts), "};", ""]

    # HEADLINE_2122
    peak_hour = diur.get("peak_hour", 6)
    min_hour  = diur.get("min_hour", 17)
    peak_div  = diur.get("peak_divergence", 0)
    min_div   = diur.get("min_divergence", 0)
    swing     = diur.get("intraday_swing", 0)
    no2_r     = _f(corr.get("no2",0), 4)
    top_corr  = list(corr.items())[0] if corr else ("unknown",0)

    lines += [
        "const HEADLINE_2122={",
        f"  n_obs:{s.get('n_obs',0)},",
        f"  n_stations:{s.get('n_stations',0)},",
        f"  mean_divergence:{_f(s.get('mean_divergence',0),4)},",
        f"  max_divergence:{_f(s.get('max_divergence',0),4)},",
        f"  pct_over_20:{_f(s.get('pct_over_20',0),4)},",
        f"  calima_hours:{c.get('n_hours',c.get('n_obs',c.get('n_days',0)))},",
        f"  calima_pct_of_obs:{_f(c.get('pct_of_valid_obs',c.get('pct_of_valid_hours',0)),4)},",
        f"  pct_public_over_calima:{_f(c.get('pct_public_over',0),2)},",
        f"  mean_aci:{_f(s.get('mean_aci',0),4)},",
        f"  mean_cmpi:{_f(s.get('mean_cmpi',0),4)},",
        f"  mean_public:{_f(s.get('mean_public',0),4)},",
        f"  max_pm10_hourly:{_f(pm.get('max_hourly',pm.get('max_daily',0)),2)},",
        f"  max_pm10_station:{pm.get('max_station','unknown')!r},",
        f"  max_pm10_date:{pm.get('max_date',str(pm.get('max_datetime',''))[:10])!r},",
        f"  peak_hour:{int(peak_hour)},",
        f"  peak_divergence:{_f(peak_div,4)},",
        f"  min_hour:{int(min_hour)},",
        f"  min_divergence:{_f(min_div,4)},",
        f"  intraday_swing:{_f(swing,4)},",
        f"  no2_r:{no2_r},",
        f"  top_correlate:{top_corr[0]!r},",
        f"  top_correlate_r:{_f(top_corr[1],4)},",
        f"  generated_at:{prov.get('generated_at','')!r},",
        f"  pipeline_version:{prov.get('pipeline_version','')!r},",
        f"  date_range:{prov.get('date_range_start','')!r}+' → '+{prov.get('date_range_end','')!r},",
        "};",
        "",
        END,
    ]
    return "\n".join(lines)


def build_2024_block(findings: dict) -> str:
    """Build the JS data block for the 2024 daily dataset."""
    s    = findings["summary"]
    prov = findings["provenance"]
    sea  = findings.get("seasonal", {})
    c    = findings.get("calima", {})
    dan  = findings.get("dana", {})
    pm   = findings.get("pm10_stats", {})
    stations = findings.get("stations", [])
    corr     = findings.get("correlations", {})
    am_list  = findings.get("air_mass", [])
    monthly  = findings.get("monthly", [])

    START, END = SENTINELS["2024"]
    lines = [
        START,
        "// GENERATED BY inject_findings.py --dataset 2024 — DO NOT EDIT MANUALLY",
        f"// Source   : {prov.get('dataset','RVVCCA 2024 daily')}",
        f"// Generated: {prov.get('generated_at','unknown')}",
        f"// Pipeline : v{prov.get('pipeline_version','?')}",
        f"// Rows     : {s.get('n_obs',0):,} valid station-days",
        f"// Resolution: Daily averages — diurnal analysis not applicable",
        "",
    ]

    # STATIONS_2024
    st_rows = []
    for st in stations:
        name = st.get("station","")
        lat  = _f(st.get("latitude") or _coord(name,"lat"), 4)
        lon  = _f(st.get("longitude") or _coord(name,"lon"), 4)
        st_rows.append(
            f"  {{station:{name!r},lat:{lat},lon:{lon},"
            f"pm10:{_f(st.get('pm10_mean',0),1)},pm25:{_f(st.get('pm25_mean',0),1)},"
            f"no2:{_f(st.get('no2_mean',0),1)},o3:{_f(st.get('o3_mean',0),1)},"
            f"aqi_sci:{_f(st.get('cmpi_mean',0),2)},aqi_public:{_f(st.get('public_mean',0),2)},"
            f"aqi_div:{_f(st.get('aqi_div_mean',0),4)},aqi_div_max:{_f(st.get('aqi_div_max',0),2)},"
            f"calima:{int(st.get('calima_days',0))},dana_days:{int(st.get('dana_days',0))},"
            f"aci:{_f(st.get('aci_mean',0),4)},n_obs:{int(st.get('n_obs',0))}}}"
        )
    lines += ["const STATIONS_2024=[", ",\n".join(st_rows), "];", ""]

    # SEASONAL_DIV
    season_order = ["Winter","Spring","Summer","Autumn"]
    season_map   = {r["season"]: r for r in sea.get("seasons",[])}
    s_parts = []
    for sn in season_order:
        row   = season_map.get(sn,{})
        color = SEASON_COLORS.get(sn,"#3a5060")
        s_parts.append(
            f"  {sn.lower()!r}:{{label:{sn!r},div:{_f(row.get('aqi_divergence',0),4)},"
            f"std:{_f(row.get('aqi_divergence_std',0),4)},pm10:{_f(row.get('pm10',0),1)},"
            f"no2:{_f(row.get('no2',0),1)},o3:{_f(row.get('o3',0),1)},"
            f"n:{int(row.get('n',0))},color:{color!r}}}"
        )
    lines += ["const SEASONAL_DIV={", ",\n".join(s_parts), "};", ""]

    # MONTHLY_DATA
    m_parts = []
    for row in sorted(monthly, key=lambda x: x.get("month",0)):
        m_parts.append(
            f"  {{month:{row.get('month',0)},name:{row.get('month_name','?')!r},"
            f"div:{_f(row.get('aqi_divergence',0),4)},pm10:{_f(row.get('pm10',0),1)},"
            f"no2:{_f(row.get('no2',0),1)},n:{int(row.get('n',0))}}}"
        )
    lines += ["const MONTHLY_DATA=[", ",\n".join(m_parts), "];", ""]

    # CORR_DATA_2024
    corr_rows = []
    for col, val in corr.items():
        label = CORR_LABELS.get(col,col)
        color = CORR_COLORS.get(col,"#3a5060")
        corr_rows.append(f"  {{var:{label!r},r:{_f(val,4)},color:{color!r}}}")
    lines += ["const CORR_DATA_2024=[", ",\n".join(corr_rows), "];", ""]

    # AM_DATA_2024
    am_parts = []
    for row in am_list:
        key   = row.get("air_mass_type","unknown")
        color = AM_COLORS.get(key,"#3a5060")
        label = AM_LABELS.get(key,key)
        am_parts.append(
            f"{key}:{{n:{int(row.get('count',0))},pct:{_f(row.get('pct',0),2)},"
            f"div:{_f(row.get('mean_div',0),4)},color:{color!r},label:{label!r}}}"
        )
    lines += ["const AM_DATA_2024={", ",\n".join(am_parts), "};", ""]

    # DANA_DATA
    lines += [
        "const DANA_DATA={",
        f"  n_days:{dan.get('n_days',0)},",
        f"  pct_of_obs:{_f(dan.get('pct_of_valid_obs',0),4)},",
        f"  mean_divergence:{_f(dan.get('mean_divergence',0),4)},",
        f"  normal_divergence:{_f(dan.get('normal_divergence',0),4)},",
        f"  calima_divergence:{_f(dan.get('calima_divergence'),4)},",
        f"  pct_public_over:{_f(dan.get('pct_public_over',0),2)},",
        f"  max_pm10_daily:{_f(dan.get('max_pm10_daily',0),2)},",
        f"  max_pm10_station:{dan.get('max_pm10_station','unknown')!r},",
        f"  max_pm10_date:{dan.get('max_pm10_date','')!r},",
        f"  event_window:{dan.get('event_window','2024-10-29 → 2024-12-15')!r},",
        "};",
        "",
    ]

    # HEADLINE_2024
    top_corr = list(corr.items())[0] if corr else ("unknown",0)
    lines += [
        "const HEADLINE_2024={",
        f"  n_obs:{s.get('n_obs',0)},",
        f"  n_stations:{s.get('n_stations',0)},",
        f"  mean_divergence:{_f(s.get('mean_divergence',0),4)},",
        f"  max_divergence:{_f(s.get('max_divergence',0),4)},",
        f"  pct_over_20:{_f(s.get('pct_over_20',0),4)},",
        f"  calima_days:{c.get('n_days',0)},",
        f"  calima_pct_of_obs:{_f(c.get('pct_of_valid_obs',c.get('pct_of_valid_hours',0)),4)},",
        f"  pct_public_over_calima:{_f(c.get('pct_public_over',0),2)},",
        f"  dana_days:{dan.get('n_days',0)},",
        f"  dana_mean_divergence:{_f(dan.get('mean_divergence',0),4)},",
        f"  mean_aci:{_f(s.get('mean_aci',0),4)},",
        f"  mean_cmpi:{_f(s.get('mean_cmpi',0),4)},",
        f"  mean_public:{_f(s.get('mean_public',0),4)},",
        f"  max_pm10_daily:{_f(pm.get('max_daily',0),2)},",
        f"  max_pm10_station:{pm.get('max_station','unknown')!r},",
        f"  max_pm10_date:{pm.get('max_date',str(pm.get('max_datetime',''))[:10])!r},",
        f"  days_exceeding_who:{pm.get('days_exceeding_who',0)},",
        f"  peak_season:{sea.get('peak_season','—')!r},",
        f"  peak_season_divergence:{_f(sea.get('peak_divergence',0),4)},",
        f"  min_season:{sea.get('min_season','—')!r},",
        f"  seasonal_swing:{_f(sea.get('seasonal_swing',0),4)},",
        f"  top_correlate:{top_corr[0]!r},",
        f"  top_correlate_r:{_f(top_corr[1],4)},",
        f"  resolution:'daily',",
        f"  generated_at:{prov.get('generated_at','')!r},",
        f"  pipeline_version:{prov.get('pipeline_version','')!r},",
        f"  date_range:{prov.get('date_range_start','')!r}+' → '+{prov.get('date_range_end','')!r},",
        "};",
        "",
        END,
    ]
    return "\n".join(lines)


# ── Injection ─────────────────────────────────────────────────────────────────

def inject(html_path: str, findings: dict, dataset: str, verbose: bool = True) -> bool:
    if not os.path.exists(html_path):
        print(f"  ✗ HTML not found: {html_path}")
        return False

    start_sentinel, end_sentinel = SENTINELS[dataset]

    with open(html_path, "r", encoding="utf-8") as f:
        html = f.read()

    if start_sentinel not in html or end_sentinel not in html:
        print(f"  ✗ Sentinels for dataset {dataset} not found in {html_path}")
        print(f"    Expected: {start_sentinel!r}")
        return False

    start = html.index(start_sentinel)
    end   = html.index(end_sentinel) + len(end_sentinel)

    if dataset == "2122":
        new_block = build_2122_block(findings)
    else:
        new_block = build_2024_block(findings)

    new_html = html[:start] + new_block + html[end:]

    with open(html_path + ".bak", "w", encoding="utf-8") as f:
        f.write(html)
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(new_html)

    if verbose:
        s   = findings["summary"]
        prov = findings["provenance"]
        print(f"  ✓ Portfolio updated [{dataset}]: {html_path}")
        print(f"    Backup : {html_path}.bak")
        print(f"    Obs    : {s['n_obs']:,} | "
              f"Mean div: {s['mean_divergence']:.4f} | "
              f"Generated: {prov['generated_at']}")
    return True


# ── CLI ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Inject pipeline findings into two-tab Strata portfolio"
    )
    parser.add_argument("--dataset",  required=True, choices=["2122","2024"],
                        help="Which dataset block to inject: 2122 or 2024")
    parser.add_argument("--html",     default=None,
                        help="Path to strata_portfolio.html (default: auto-detect)")
    parser.add_argument("--findings", default=None,
                        help="Path to findings JSON (default: dataset-appropriate path)")
    parser.add_argument("--dry-run",  action="store_true",
                        help="Print the generated JS block without writing to HTML")
    args = parser.parse_args()

    html_path = args.html or DEFAULT_HTML

    if args.findings:
        findings_path = args.findings
    else:
        findings_path = FINDINGS_2122 if args.dataset == "2122" else FINDINGS_2024

    if not os.path.exists(findings_path):
        print(f"✗ Findings not found: {findings_path}")
        if args.dataset == "2122":
            print("  Run: python src/run_pipeline.py  (with 2021-2022 data)")
        else:
            print("  Run: python src/run_pipeline.py --fetch")
        sys.exit(1)

    with open(findings_path) as f:
        findings = json.load(f)

    if args.dry_run:
        if args.dataset == "2122":
            print(build_2122_block(findings))
        else:
            print(build_2024_block(findings))
        sys.exit(0)

    success = inject(html_path, findings, args.dataset, verbose=True)
    sys.exit(0 if success else 1)
