"""
inject_findings.py
------------------
Reads outputs/reports/aeris_findings.json and injects ALL pipeline-derived
data into aeris_portfolio.html, replacing every scientific value between
the sentinel comments with values computed from real RVVCCA data.

Data flow enforced:
  aeris_processed.csv → analysis.py → findings.json → inject_findings.py → HTML

Usage:
  python src/inject_findings.py
  python src/inject_findings.py --html path/to/aeris_portfolio.html
  python src/inject_findings.py --dry-run
"""

import json
import os
import sys
import math
import argparse
from datetime import datetime

sys.path.insert(0, os.path.dirname(__file__))
from config import OUTPUT_PATH

FINDINGS_PATH = os.path.join(OUTPUT_PATH, "reports", "aeris_findings.json")
DEFAULT_HTML  = os.path.join(os.path.dirname(__file__), "..", "aeris_portfolio.html")

START_SENTINEL = "// __AERIS_DATA_START__"
END_SENTINEL   = "// __AERIS_DATA_END__"

# Atmospheric colour semantics — kept in injector so colours are consistent
AM_COLORS = {
    "stagnant_mix":    "#1e2e3c",
    "marine_air":      "#00d4ff",
    "saharan_dust":    "#ff9a00",
    "urban_pollution": "#ff4455",
}
AM_LABELS = {
    "stagnant_mix":    "Stagnant mix",
    "marine_air":      "Marine air",
    "saharan_dust":    "Saharan dust",
    "urban_pollution": "Urban pollution",
}
CORR_COLORS = {
    "no2":            "#ff4455",
    "temperature":    "#ff9a00",
    "pm25":           "#ffb347",
    "ACI_normalized": "#8b6fff",
    "pm10":           "#ff9a00",
    "o3":             "#00d4ff",
    "wind_speed":     "#39d98a",
    "humidity":       "#3a5060",
}
CORR_LABELS = {
    "no2":            "NO\u2082",
    "temperature":    "Temperature",
    "pm25":           "PM2.5",
    "ACI_normalized": "ACI",
    "pm10":           "PM10",
    "o3":             "O\u2083",
    "wind_speed":     "Wind speed",
    "humidity":       "Humidity",
}

# Station coordinates (not in dataset — fixed geographic facts)
STATION_COORDS = {
    "Avda. Francia":             {"lat": 39.4632, "lon": -0.3451},
    "Av. Francia":               {"lat": 39.4632, "lon": -0.3451},
    "Bulevard Sud":              {"lat": 39.4501, "lon": -0.3928},
    "Conselleria Meteo":         {"lat": 39.4700, "lon": -0.3700},
    "Moli del Sol":              {"lat": 39.4447, "lon": -0.3802},
    "Molí del Sol":              {"lat": 39.4447, "lon": -0.3802},
    "Nazaret Meteo":             {"lat": 39.4540, "lon": -0.3370},
    "Natzaret Meteo":            {"lat": 39.4540, "lon": -0.3370},
    "Pista Silla":               {"lat": 39.4298, "lon": -0.4083},
    "Pista de Silla":            {"lat": 39.4298, "lon": -0.4083},
    "Politecnico":               {"lat": 39.4800, "lon": -0.3463},
    "Politècnic":                {"lat": 39.4800, "lon": -0.3463},
    "Puerto llit antic":         {"lat": 39.4590, "lon": -0.3280},
    "Puerto llit antic Turia":   {"lat": 39.4590, "lon": -0.3280},
    "Puerto Moll Trans.":        {"lat": 39.4510, "lon": -0.3190},
    "Puerto Moll Trans. Ponent": {"lat": 39.4510, "lon": -0.3190},
    "Valencia Centro":           {"lat": 39.4698, "lon": -0.3763},
    "Valencia Olivereta":        {"lat": 39.4680, "lon": -0.4050},
    "Viveros":                   {"lat": 39.4793, "lon": -0.3640},
}


def _f(val, decimals=3):
    if val is None or (isinstance(val, float) and math.isnan(val)):
        return 0.0
    return round(float(val), decimals)


def _get_coord(station_name, key):
    """Look up lat/lon for a station name with fuzzy fallback."""
    if station_name in STATION_COORDS:
        return STATION_COORDS[station_name][key]
    name_lower = str(station_name).lower()
    for k, v in STATION_COORDS.items():
        if k.lower() in name_lower or name_lower in k.lower():
            return v[key]
    # Last resort: use value from findings if present
    return 0.0


def build_data_block(findings: dict) -> str:
    """
    Build the complete JS data block from findings.
    Every value here is pipeline-derived — no hardcoding.
    """
    s   = findings['summary']
    d   = findings['diurnal']
    prov = findings['provenance']
    c   = findings.get('calima', {})
    pm  = findings.get('pm10_stats', {})
    stations = findings.get('stations', [])
    corr     = findings.get('correlations', {})
    am_list  = findings.get('air_mass', [])

    lines = [
        START_SENTINEL,
        "// GENERATED BY inject_findings.py — DO NOT EDIT MANUALLY",
        f"// Source  : {prov.get('dataset', 'RVVCCA')}",
        f"// Generated: {prov.get('generated_at', 'unknown')}",
        f"// Pipeline : v{prov.get('pipeline_version', '?')}",
        f"// Rows     : {s.get('n_obs', 0):,} valid station-hours",
        f"// Stations : {s.get('n_stations', 0)}",
        f"// Period   : {prov.get('date_range_start')} → {prov.get('date_range_end')}",
        "",
    ]

    # ── STATIONS (fully pipeline-derived) ─────────────────────────────────────
    st_rows = []
    for st in stations:
        name = st.get('station', '')
        lat = _f(st.get('latitude') or _get_coord(name, 'lat'), 4)
        lon = _f(st.get('longitude') or _get_coord(name, 'lon'), 4)
        st_rows.append(
            f"  {{station:{name!r},"
            f"lat:{lat},lon:{lon},"
            f"pm10:{_f(st.get('pm10_mean',0),1)},"
            f"pm25:{_f(st.get('pm25_mean',0),1)},"
            f"no2:{_f(st.get('no2_mean',0),1)},"
            f"o3:{_f(st.get('o3_mean',0),1)},"
            f"aqi_sci:{_f(st.get('cmpi_mean',0),2)},"
            f"aqi_public:{_f(st.get('public_mean',0),2)},"
            f"aqi_div:{_f(st.get('aqi_div_mean',0),4)},"
            f"aqi_div_max:{_f(st.get('aqi_div_max',0),2)},"
            f"calima:{int(st.get('calima_hours',0))},"
            f"aci:{_f(st.get('aci_mean',0),4)},"
            f"n_obs:{int(st.get('n_obs',0))}}}"
        )
    lines.append("const STATIONS=[")
    lines.append(",\n".join(st_rows))
    lines.append("];")
    lines.append("")

    # ── HOURLY_DIV (pipeline-derived, rounded to 4dp) ─────────────────────────
    div_arr = d.get('divergence_array', [])
    if div_arr:
        lines.append(f"// Mean CMPI divergence by hour — peak {d['peak_hour']:02d}:00 "
                     f"({d['peak_divergence']:.4f} pts), min {d['min_hour']:02d}:00 "
                     f"({d['min_divergence']:.4f} pts)")
        lines.append(f"const HOURLY_DIV=[{','.join(str(_f(v,4)) for v in div_arr)}];")
    else:
        lines.append("const HOURLY_DIV=[];")
    lines.append("")

    # ── O3_SCHEMATIC (labelled as schematic — not pipeline data) ─────────────
    lines.append("// O3 diurnal schematic — illustrative only, not pipeline-derived")
    lines.append("const O3_SCHEMATIC=[28,24,21,19,18,20,25,33,42,52,62,71,78,83,87,89,88,85,79,70,58,47,38,33];")
    lines.append("")

    # ── CORR_DATA (pipeline-derived) ──────────────────────────────────────────
    corr_rows = []
    for col, val in corr.items():
        label = CORR_LABELS.get(col, col)
        color = CORR_COLORS.get(col, '#3a5060')
        corr_rows.append(f"  {{var:{label!r},r:{_f(val,4)},color:{color!r}}}")
    lines.append("const CORR_DATA=[")
    lines.append(",\n".join(corr_rows))
    lines.append("];")
    lines.append("")

    # ── AM_DATA (pipeline-derived) ────────────────────────────────────────────
    am_parts = []
    for row in am_list:
        key   = row.get('air_mass_type', 'unknown')
        color = AM_COLORS.get(key, '#3a5060')
        label = AM_LABELS.get(key, key)
        am_parts.append(
            f"{key}:{{n:{int(row.get('count',0))},"
            f"pct:{_f(row.get('pct',0),2)},"
            f"div:{_f(row.get('mean_div',0),4)},"
            f"color:{color!r},"
            f"label:{label!r}}}"
        )
    lines.append("const AM_DATA={")
    lines.append(",\n".join(am_parts))
    lines.append("};")
    lines.append("")

    # ── HEADLINE_STATS (pipeline-derived — used by cover & metric row) ─────────
    max_pm10_station = pm.get('max_station', 'unknown')
    max_pm10_date    = pm.get('max_datetime', '')[:10]
    calima_n         = c.get('n_hours', 0)
    calima_pct_over  = c.get('pct_public_over', 0)

    lines.append("// Headline statistics — all pipeline-derived")
    lines.append(f"const HEADLINE={{")
    lines.append(f"  n_obs:{s.get('n_obs',0)},")
    lines.append(f"  n_stations:{s.get('n_stations',0)},")
    lines.append(f"  mean_divergence:{_f(s.get('mean_divergence',0),4)},")
    lines.append(f"  max_divergence:{_f(s.get('max_divergence',0),4)},")
    lines.append(f"  calima_hours:{calima_n},")
    lines.append(f"  calima_pct_of_obs:{_f(c.get('pct_of_valid_obs',0),4)},")
    lines.append(f"  pct_public_over_calima:{_f(calima_pct_over,2)},")
    lines.append(f"  mean_aci:{_f(s.get('mean_aci',0),4)},")
    lines.append(f"  mean_cmpi:{_f(s.get('mean_cmpi',0),4)},")
    lines.append(f"  mean_public:{_f(s.get('mean_public',0),4)},")
    lines.append(f"  max_pm10_hourly:{_f(pm.get('max_hourly',0),2)},")
    lines.append(f"  max_pm10_station:{max_pm10_station!r},")
    lines.append(f"  max_pm10_date:{max_pm10_date!r},")
    lines.append(f"  peak_hour:{d.get('peak_hour',0)},")
    lines.append(f"  peak_divergence:{_f(d.get('peak_divergence',0),4)},")
    lines.append(f"  min_hour:{d.get('min_hour',0)},")
    lines.append(f"  min_divergence:{_f(d.get('min_divergence',0),4)},")
    lines.append(f"  intraday_swing:{_f(d.get('intraday_swing',0),4)},")
    lines.append(f"  no2_r:{_f(findings['correlations'].get('no2',0),4)},")
    lines.append(f"  generated_at:{prov.get('generated_at','')!r},")
    lines.append(f"  pipeline_version:{prov.get('pipeline_version','')!r},")
    lines.append(f"  date_range:{prov.get('date_range_start','')!r}+' → '+{prov.get('date_range_end','')!r},")
    lines.append(f"}};")
    lines.append("")

    lines.append(END_SENTINEL)
    return "\n".join(lines)


def inject(html_path: str, findings: dict, verbose: bool = True) -> bool:
    if not os.path.exists(html_path):
        print(f"  ✗ HTML not found: {html_path}")
        return False

    with open(html_path, 'r', encoding='utf-8') as f:
        html = f.read()

    if START_SENTINEL not in html or END_SENTINEL not in html:
        print(f"  ✗ Sentinels not found in {html_path}")
        return False

    start = html.index(START_SENTINEL)
    end   = html.index(END_SENTINEL) + len(END_SENTINEL)
    new_block = build_data_block(findings)
    new_html  = html[:start] + new_block + html[end:]

    # Backup
    with open(html_path + '.bak', 'w', encoding='utf-8') as f:
        f.write(html)

    with open(html_path, 'w', encoding='utf-8') as f:
        f.write(new_html)

    if verbose:
        s  = findings['summary']
        pm = findings.get('pm10_stats', {})
        print(f"  ✓ Portfolio updated: {html_path}")
        print(f"    Backup: {html_path}.bak")
        print(f"    Observations: {s['n_obs']:,} | "
              f"Mean div: {s['mean_divergence']:.4f} | "
              f"Calima: {findings.get('calima',{}).get('n_hours',0):,}h | "
              f"Max PM10: {pm.get('max_hourly',0):.1f} µg/m³ "
              f"at {pm.get('max_station','?')}")
        print(f"    Generated: {findings['provenance']['generated_at']}")

    return True


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--html', default=None)
    parser.add_argument('--findings', default=None)
    parser.add_argument('--dry-run', action='store_true')
    args = parser.parse_args()

    findings_path = args.findings or FINDINGS_PATH
    html_path     = args.html or DEFAULT_HTML

    if not os.path.exists(findings_path):
        print(f"✗ Findings not found: {findings_path}")
        print("Run: python src/run_pipeline.py")
        sys.exit(1)

    with open(findings_path) as f:
        findings = json.load(f)

    if args.dry_run:
        print(build_data_block(findings))
        sys.exit(0)

    success = inject(html_path, findings, verbose=True)
    sys.exit(0 if success else 1)
